### ISSUE TITLE
a way to reference breakpoint for conditional rendering

### ISSUE THREAD

**Issue by linh-ebisolvn** [tailwindcss/designing-with-tailwindcss#20]
I cannot find a way to sort of somehow can figure out the viewport screen size to manipulate with.
What I want is like in vuetify and material UI they come with breakpoint context so you can either choose to render the element or not. Right now the responsive utility class only set their display style to either hidden or block

**Comment by adamwathan** [comment]
Hey! Tailwind is just a CSS framework, you should write some JavaScript if you need to do this 👍🏻
